[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"
watchPaths = ["frontend/**"]

[deploy]
startCommand = "npm run serve"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
VITE_NODE_ENV = "production" 