[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"
watchPaths = ["frontend/**"]

[deploy]
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
VITE_NODE_ENV = "production"

[nixpacks]
package = "nodejs" 