[build]
builder = "NIXPACKS"
buildCommand = "npm install --no-audit --no-fund && npm run build"
watchPaths = ["frontend/**"]

[deploy]
startCommand = "npm run serve"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
VITE_NODE_ENV = "production"
NPM_CONFIG_CACHE = "/tmp/npm-cache"
NPM_CONFIG_UPDATE_NOTIFIER = "false"
NPM_CONFIG_AUDIT = "false" 