[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm ci && npm run build"
]

[start]
cmd = "python run.py"

[variables]
PYTHONPATH = "." 