[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "npm", "pip"]
aptPkgs = []

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "python main.py"

[variables]
PYTHONPATH = "."
NIXPACKS_BUILD_TIME_ENV_INLINE = "true" 