[variables]
NODE_VERSION = "20"
PYTHON_VERSION = "3.11.6"

[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
    "cd frontend && npm ci",
    "python -m venv venv",
    "source venv/bin/activate && pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "chmod +x start.sh"
]

[start]
cmd = "./start.sh" 