# Configuración para proyecto full-stack React + FastAPI
[variables]
NIXPACKS_PYTHON_VERSION = "3.12"
PYTHONPATH = "."

# Providers como string separado por comas
providers = "python,node"

# Fases de build
[phases.setup]
nixPkgs = ["python312", "nodejs-18_x"]

[phases.install] 
cmds = [
    "cd frontend && npm install",
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[phases.start]
cmd = "python3 -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT" 