[variables]
NODE_VERSION = "20"
PYTHON_VERSION = "3.11.6"

[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "cd frontend && npm ci",
    "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT" 