[build]
builder = "nixpacks"

[deploy]
buildCommand = "./build.sh"
startCommand = "python3 -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

[build.environment]
PYTHONPATH = "."
NIXPACKS_PYTHON_VERSION = "3.11" 