[build]
builder = "nixpacks"
watchPaths = ["backend/**", "*.py", "requirements.txt", "main.py", "rag/**", "railway.toml"]

[deploy]
startCommand = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT --no-access-log"

[build.environment]
PYTHONPATH = "."
NIXPACKS_PYTHON_VERSION = "3.11.6"

[variables]
RAILWAY_RUNTIME = "python" 