[build]
builder = "nixpacks"
watchPaths = ["backend/**", "start_server.py", "requirements.txt", "rag/**", "railway.toml", "supabase_integration.py"]

[deploy]
startCommand = "python start_server.py"

[build.environment]
PYTHONPATH = "."
NIXPACKS_PYTHON_VERSION = "3.11.6"

[variables]
RAILWAY_RUNTIME = "python" 