[build]
builder = "nixpacks"
watchPaths = ["backend/**", "*.py", "requirements.txt", "main.py", "rag/**", "railway.toml"]

[deploy]
startCommand = "python main.py"

[build.environment]
PYTHONPATH = "."
NIXPACKS_PYTHON_VERSION = "3.11.6"

[variables]
RAILWAY_RUNTIME = "python" 